language: cpp

matrix:
  include:
    - env: BUILD_TYPE=Debug   CXX_STANDARD=11
      compiler: clang

    - env: BUILD_TYPE=Debug   CXX_STANDARD=11
      compiler: gcc

    - env: BUILD_TYPE=Release CXX_STANDARD=11
      compiler: clang

    - env: BUILD_TYPE=Release CXX_STANDARD=11
      compiler: gcc

    - env: BUILD_TYPE=Release CXX_STANDARD=17
      compiler: clang
      dist: bionic

    - env: BUILD_TYPE=Release CXX_STANDARD=17
      compiler: gcc
      dist: bionic

script:
  - ./build.sh
